export { Navbar } from './navbar/Navbar'
export { Landing } from './landing/Landing'
export { Skills } from './skills/Skills'
export { Projects } from './projects/Projects'
export { Contact } from './contact/Contact'
