import Head from 'next/head'
import localFont from '@next/font/local'
import Name from '@/components/Name'
import Nav from '@/components/Nav'

const Bogam = localFont({ src: '../public/Bogam.woff2' })

export default function Home() {
  return (
    <>
      <Head>
        <title>TGB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className={Bogam.className}>
        <Name />
      </div>
    </>
  )
}
